[package]
name = "hello-rama-web"
version = "0.6.0"
edition = "2024"
authors = ["Jeffery D. Mitchell", "<crusty.rustacean@gmail.com>"]
description = "A playground for learning how to build a web server with Rama"
readme = "README.md"
repository = "https://github.com/crustyrustacean/hello-rama-web.git"
license = "MIT"
publish = false

[[bin]]
name = "hello-rama-web"
path = "src/bin/main.rs"

[dependencies]
rama = { git = "https://github.com/plabayo/rama.git", tag = "rama-0.3.0-alpha.3", features = [ "http", "http-full" ] }
tokio = { version = "1.48.0", features = ["full"] }

